import type { InstrumentType } from '@/types/sonic';
import { GENRE_TEMPLATES, type GenreKey } from '@/lib/music/genreTemplates';
import type { Density } from './types';

export type GenreStyleTraits = {
    genre: GenreKey;
    aliases: string[];
    bpmRange: [number, number];
    defaultBpm: number;
    key: string;
    scale: string;
    drumFeel: string;
    bassRole: string;
    harmony: string;
    leadRole: string;
    soundPalette: string[];
    arrangement: string;
    density: Density;
    requiredTracks: InstrumentType[];
    failureModes: string[];
};

const template = (genre: GenreKey) => GENRE_TEMPLATES[genre];

export const GENRE_STYLE_TRAITS: Partial<Record<GenreKey, GenreStyleTraits>> & { generic: GenreStyleTraits } = {
    rock: {
        genre: 'rock',
        aliases: template('rock').aliases,
        bpmRange: [124, 148],
        defaultBpm: 136,
        key: 'E minor',
        scale: 'E minor',
        drumFeel: 'Kick variations around a clear snare backbeat on beats 2 and 4.',
        bassRole: 'Root-note eighths with small walks into the riff.',
        harmony: 'Minor pentatonic power-chord movement built from root and fifth.',
        leadRole: 'Short distorted guitar-like riff, sparse enough to be memorable.',
        soundPalette: ['RolandTR909 drums', 'sawtooth power chords', 'triangle or saw bass', 'controlled distortion'],
        arrangement: 'Four or eight bar core loop with a recognizable riff and occasional gaps.',
        density: 'balanced',
        requiredTracks: ['drums', 'bass', 'melody'],
        failureModes: ['generic techno four-on-floor', 'random high notes', 'missing guitar-like riff', 'too much distortion'],
    },
    punk: {
        genre: 'punk',
        aliases: template('punk').aliases,
        bpmRange: [165, 188],
        defaultBpm: 176,
        key: 'A minor',
        scale: 'A minor',
        drumFeel: 'Fast hats with backbeat snare and compact kick doubles.',
        bassRole: 'Driving root notes that follow the guitar rhythm.',
        harmony: 'Simple power chords and downstroke energy.',
        leadRole: 'Short aggressive riff or chord chop.',
        soundPalette: ['tight 909 kit', 'short sawtooth chords', 'filtered bass'],
        arrangement: 'Direct core loop with no ambient wash.',
        density: 'dense',
        requiredTracks: ['drums', 'bass', 'melody'],
        failureModes: ['slow rock tempo', 'ambient pads', 'overly complex chords'],
    },
    metal: {
        genre: 'metal',
        aliases: template('metal').aliases,
        bpmRange: [140, 170],
        defaultBpm: 150,
        key: 'E minor',
        scale: 'E minor',
        drumFeel: 'Tight kick pulse or double-kick with strong snare anchors.',
        bassRole: 'Low root support locked to palm-muted guitar rhythm.',
        harmony: 'Dark root/fifth chugs with restrained movement.',
        leadRole: 'Low chug or octave/fifth riff, filtered to avoid harsh fizz.',
        soundPalette: ['909 kick/snare', 'low saw chug', 'controlled distortion', 'low-pass filtering'],
        arrangement: 'Heavy core loop with rhythmic stops and no muddy FX bed.',
        density: 'dense',
        requiredTracks: ['drums', 'bass', 'melody'],
        failureModes: ['clipping', 'muddy bass/kick overlap', 'random shred notes'],
    },
    funk: {
        genre: 'funk',
        aliases: template('funk').aliases,
        bpmRange: [94, 116],
        defaultBpm: 104,
        key: 'C minor',
        scale: 'C minor',
        drumFeel: 'Syncopated kick with snappy backbeat and quiet hats.',
        bassRole: 'Active syncopated bass carries the groove.',
        harmony: 'Clipped minor chord stabs on gaps.',
        leadRole: 'Short stabs, not a long lead line.',
        soundPalette: ['808/909 hybrid drums', 'triangle bass', 'square stabs'],
        arrangement: 'Pocket-first loop with rests and call-response.',
        density: 'balanced',
        requiredTracks: ['drums', 'bass'],
        failureModes: ['straight techno kick', 'static bass', 'no syncopation'],
    },
    pop_funk: {
        genre: 'pop_funk',
        aliases: template('pop_funk').aliases,
        bpmRange: [108, 122],
        defaultBpm: 116,
        key: 'F minor',
        scale: 'F minor pentatonic',
        drumFeel: 'Tight dance-pop backbeat with syncopated kick and bright hats.',
        bassRole: 'Syncopated low-register bass that carries the groove without copying any song.',
        harmony: 'Minor pentatonic pop-funk movement with short stabs.',
        leadRole: 'Short bright hook or stab, not an artist melody quotation.',
        soundPalette: ['808/909 hybrid drums', 'triangle bass', 'square stabs', 'light noise lift'],
        arrangement: 'Danceable core loop with drums, bass, and one short original hook.',
        density: 'balanced',
        requiredTracks: ['drums', 'bass', 'melody'],
        failureModes: ['generic C minor fallback', 'copying a recognizable artist melody', 'drum-only carryover'],
    },
    pop: {
        genre: 'pop',
        aliases: template('pop').aliases,
        bpmRange: [100, 124],
        defaultBpm: 118,
        key: 'C major',
        scale: 'C major',
        drumFeel: 'Clean beat with uncluttered backbeat.',
        bassRole: 'Supportive roots that leave space for the hook.',
        harmony: 'Familiar diatonic chord loop.',
        leadRole: 'Simple singable hook.',
        soundPalette: ['808 kick', '909 clap', 'sine or piano hook', 'triangle bass'],
        arrangement: 'Accessible core loop with one clear hook.',
        density: 'balanced',
        requiredTracks: ['drums', 'bass', 'melody'],
        failureModes: ['too abstract', 'no hook', 'overly harsh synths'],
    },
    jazz: {
        genre: 'jazz',
        aliases: template('jazz').aliases,
        bpmRange: [78, 112],
        defaultBpm: 92,
        key: 'D minor',
        scale: 'D minor',
        drumFeel: 'Soft brushed-feel hats/snare with understated kick.',
        bassRole: 'Walking contour using chord tones.',
        harmony: 'Warm extended chords or piano-like voicings.',
        leadRole: 'Sparse chord color over walking bass.',
        soundPalette: ['soft hats', 'triangle bass', 'piano chords'],
        arrangement: 'Relaxed loop with room for swing-like phrasing.',
        density: 'sparse',
        requiredTracks: ['bass', 'melody'],
        failureModes: ['hard techno drums', 'static bass', 'too bright'],
    },
    hiphop: {
        genre: 'hiphop',
        aliases: template('hiphop').aliases,
        bpmRange: [78, 104],
        defaultBpm: 92,
        key: 'F minor',
        scale: 'F minor',
        drumFeel: 'Punchy half-time kick/snare, dry clap support, and quiet uneven hats.',
        bassRole: 'Low 808-style sine bass under the beat, mostly F minor roots.',
        harmony: 'Very sparse minor color; do not fill the loop with chords.',
        leadRole: 'No lead melody by default; leave space for rap vocals unless the prompt asks for a hook.',
        soundPalette: ['808 kick', '909 snare', 'dry clap', 'quiet hats', 'low sine sub', 'low-gain texture'],
        arrangement: 'Vocal-friendly rap beat with drums and bass forward, minimal top-line material.',
        density: 'sparse',
        requiredTracks: ['drums', 'bass'],
        failureModes: ['busy melodic sine hook', 'four-on-floor house beat', 'weak snare', 'too much harmony for a rap vocal bed'],
    },
    latin: {
        genre: 'latin',
        aliases: template('latin').aliases,
        bpmRange: [100, 122],
        defaultBpm: 116,
        key: 'A minor',
        scale: 'A minor',
        drumFeel: 'Syncopated percussion with bright but quiet upper hits.',
        bassRole: 'Warm bass accents around the clave-like rhythm.',
        harmony: 'Minor-key bell or chord accents.',
        leadRole: 'Bright short accents.',
        soundPalette: ['808 kick', 'clap', 'pink percussion', 'triangle bass'],
        arrangement: 'Percussion-forward groove with tonal restraint.',
        density: 'balanced',
        requiredTracks: ['drums', 'bass'],
        failureModes: ['straight generic house', 'overloud percussion', 'no syncopation'],
    },
    reggae: {
        genre: 'reggae',
        aliases: template('reggae').aliases,
        bpmRange: [68, 86],
        defaultBpm: 76,
        key: 'G minor',
        scale: 'G minor',
        drumFeel: 'Laid-back one-drop feel.',
        bassRole: 'Deep spacious bass with long rests.',
        harmony: 'Offbeat chord chops.',
        leadRole: 'Dubby chord stab rather than busy melody.',
        soundPalette: ['808 kick', '909 snare', 'triangle bass', 'square offbeat chops', 'delay'],
        arrangement: 'Slow pocket with dub space.',
        density: 'sparse',
        requiredTracks: ['drums', 'bass', 'melody'],
        failureModes: ['too fast', 'straight techno hats', 'no offbeat chops'],
    },
    techno: {
        genre: 'techno',
        aliases: template('techno').aliases,
        bpmRange: [126, 140],
        defaultBpm: 132,
        key: 'C minor',
        scale: 'C minor',
        drumFeel: 'Stable four-on-floor kick with clap and hats.',
        bassRole: 'Dark filtered bass pulse separated from kick.',
        harmony: 'Minimal minor stabs.',
        leadRole: 'Short dark synth stab or none.',
        soundPalette: ['909 kit', 'filtered saw bass', 'supersaw stab', 'pink riser'],
        arrangement: 'Hypnotic core loop with controlled filter motion.',
        density: 'balanced',
        requiredTracks: ['drums', 'bass'],
        failureModes: ['muddy kick/bass', 'too many leads', 'unstable tempo'],
    },
    italo_80s: {
        genre: 'italo_80s',
        aliases: template('italo_80s').aliases,
        bpmRange: [118, 128],
        defaultBpm: 124,
        key: 'C minor',
        scale: 'C minor',
        drumFeel: 'Retro electro 4/4 with bright hats.',
        bassRole: 'Octave-jump square bass.',
        harmony: 'Neon minor arpeggio.',
        leadRole: 'Bright arpeggio with delay.',
        soundPalette: ['808/909 electro kit', 'square bass', 'saw arpeggio', 'small delay'],
        arrangement: 'Retro dance loop with variation on repeat requests.',
        density: 'balanced',
        requiredTracks: ['drums', 'bass', 'melody'],
        failureModes: ['generic dark techno', 'no octave bass', 'too modern/industrial'],
    },
    italo_80s_alt: {
        genre: 'italo_80s_alt',
        aliases: template('italo_80s_alt').aliases,
        bpmRange: [118, 128],
        defaultBpm: 124,
        key: 'A minor',
        scale: 'A minor',
        drumFeel: 'Snappier electro drums than the first Italo pass.',
        bassRole: 'Alternate octave-jump square bass.',
        harmony: 'Brighter minor arpeggio variation.',
        leadRole: 'Variation arpeggio, not the same riff.',
        soundPalette: ['808 kick', '909 snare', 'square bass', 'saw arpeggio'],
        arrangement: 'Second-pass variation.',
        density: 'balanced',
        requiredTracks: ['drums', 'bass', 'melody'],
        failureModes: ['replaying identical code', 'generic techno fallback'],
    },
    house: {
        genre: 'house',
        aliases: template('house').aliases,
        bpmRange: [120, 128],
        defaultBpm: 124,
        key: 'C major',
        scale: 'C major',
        drumFeel: 'Four-on-floor with clap and offbeat hats.',
        bassRole: 'Warm bass on downbeats and gaps.',
        harmony: 'Simple piano or square chord stabs.',
        leadRole: 'Warm chord color, no harsh lead.',
        soundPalette: ['808 kick', '909 clap', 'offbeat hats', 'triangle bass', 'piano stabs'],
        arrangement: 'Groove-first dance loop.',
        density: 'balanced',
        requiredTracks: ['drums', 'bass'],
        failureModes: ['missing offbeat hat', 'cold techno bass', 'overbright lead'],
    },
    ambient: {
        genre: 'ambient',
        aliases: template('ambient').aliases,
        bpmRange: [60, 86],
        defaultBpm: 72,
        key: 'C major',
        scale: 'C major',
        drumFeel: 'No drums unless explicitly requested.',
        bassRole: 'Soft long low tones.',
        harmony: 'Slow suspended chord movement.',
        leadRole: 'Evolving pads and FX.',
        soundPalette: ['sine pad', 'long room', 'delay', 'filtered noise'],
        arrangement: 'Slow evolving loop with heavy space.',
        density: 'sparse',
        requiredTracks: ['fx'],
        failureModes: ['forced beat', 'short harsh envelopes', 'too busy'],
    },
    dnb: {
        genre: 'dnb',
        aliases: template('dnb').aliases,
        bpmRange: [168, 178],
        defaultBpm: 174,
        key: 'C minor',
        scale: 'C minor',
        drumFeel: 'Fast broken beat with 16th hats.',
        bassRole: 'Rolling filtered bass.',
        harmony: 'Minimal dark motif.',
        leadRole: 'Small high note or none.',
        soundPalette: ['909 breakbeat kit', 'filtered saw bass', 'quiet sine lead'],
        arrangement: 'High-energy loop with controlled density.',
        density: 'dense',
        requiredTracks: ['drums', 'bass'],
        failureModes: ['straight four-on-floor', 'slow BPM', 'no breakbeat'],
    },
    trance: {
        genre: 'trance',
        aliases: template('trance').aliases,
        bpmRange: [132, 142],
        defaultBpm: 138,
        key: 'A minor',
        scale: 'A minor',
        drumFeel: 'Driving kick with offbeat bass and hats.',
        bassRole: 'Offbeat saw bass.',
        harmony: 'Uplifting arpeggio from minor chord tones.',
        leadRole: 'Airy supersaw arpeggio.',
        soundPalette: ['909 kit', 'saw bass', 'supersaw arp', 'pink riser'],
        arrangement: 'Driving loop with spacious FX.',
        density: 'dense',
        requiredTracks: ['drums', 'bass', 'melody'],
        failureModes: ['flat chord pad', 'no arp', 'too low energy'],
    },
    acid: {
        genre: 'acid',
        aliases: template('acid').aliases,
        bpmRange: [124, 132],
        defaultBpm: 128,
        key: 'A minor',
        scale: 'A minor',
        drumFeel: 'Simple 4/4 foundation.',
        bassRole: '303-style resonant saw pattern.',
        harmony: 'Bassline is the hook.',
        leadRole: 'Filter movement rather than separate melody.',
        soundPalette: ['909 kit', 'resonant saw bass', 'filter sweep'],
        arrangement: 'Hypnotic squelch loop.',
        density: 'balanced',
        requiredTracks: ['drums', 'bass'],
        failureModes: ['no resonance', 'too many chords', 'missing 303 feel'],
    },
    minimal: {
        genre: 'minimal',
        aliases: template('minimal').aliases,
        bpmRange: [120, 130],
        defaultBpm: 126,
        key: 'C minor',
        scale: 'C minor',
        drumFeel: 'Sparse kick and subtle hats.',
        bassRole: 'Hypnotic short bass loop.',
        harmony: 'Little or no melody.',
        leadRole: 'None unless requested.',
        soundPalette: ['909 kick', 'quiet hats', 'triangle bass'],
        arrangement: 'Sparse hypnotic repetition with tiny changes.',
        density: 'sparse',
        requiredTracks: ['drums', 'bass'],
        failureModes: ['too many layers', 'busy melody', 'overly loud hats'],
    },
    drums: {
        genre: 'drums',
        aliases: template('drums').aliases,
        bpmRange: [90, 140],
        defaultBpm: 120,
        key: 'N/A',
        scale: 'N/A',
        drumFeel: 'Kick, snare, and hats only.',
        bassRole: 'No bass.',
        harmony: 'No harmony.',
        leadRole: 'No melody.',
        soundPalette: ['synth kick', 'pink snare', 'quiet hats'],
        arrangement: 'Drum-only loop.',
        density: 'balanced',
        requiredTracks: ['drums'],
        failureModes: ['adding bass or melody', 'tonal synth pretending to be drums'],
    },
    clean_drums: {
        ...templateTraitsFrom('drums', 'clean_drums', 'Clean drum-only backbeat with balanced sample-safe gains.'),
    },
    tight_clean_drums: {
        ...templateTraitsFrom('drums', 'tight_clean_drums', 'Extra-tight clean drums with minimal high end.'),
    },
    double_tap_drums: {
        ...templateTraitsFrom('drums', 'double_tap_drums', 'Drum-only loop with two-hit subdivisions.'),
    },
    triple_tap_drums: {
        ...templateTraitsFrom('drums', 'triple_tap_drums', 'Drum-only loop with three-hit subdivisions.'),
    },
    low_drums: {
        ...templateTraitsFrom('drums', 'low_drums', 'Lower, darker drum-only loop.'),
    },
    humanized_drums: {
        ...templateTraitsFrom('drums', 'humanized_drums', 'Humanized drum-only loop with controlled syncopation.'),
    },
    repaired_drums: {
        ...templateTraitsFrom('drums', 'repaired_drums', 'Simplified repaired drum-only loop.'),
    },
    pop_punk_drums: {
        ...templateTraitsFrom('punk', 'pop_punk_drums', 'Pop-punk drum traits: fast hats and strong backbeat.'),
    },
    punk_fast_hats: {
        ...templateTraitsFrom('punk', 'punk_fast_hats', 'Fast punk hats with drum-only scope.'),
    },
    metal_double_kick: {
        ...templateTraitsFrom('metal', 'metal_double_kick', 'Metal double-kick drums only.'),
    },
    boom_bap_drums: {
        ...templateTraitsFrom('hiphop', 'boom_bap_drums', 'Boom-bap drums only.'),
    },
    dnb_breakbeat: {
        ...templateTraitsFrom('dnb', 'dnb_breakbeat', 'DnB breakbeat drums only.'),
    },
    clean_rock: {
        ...templateTraitsFrom('rock', 'clean_rock', 'Cleaner rock repair with reduced distortion and gain.'),
    },
    humanized_rock: {
        ...templateTraitsFrom('rock', 'humanized_rock', 'Humanized rock with syncopated kick and riff gaps.'),
    },
    grimes_m4m: {
        ...templateTraitsFrom('generic', 'grimes_m4m', 'Reference-inspired Music 4 Machines traits; do not copy the full source script.'),
    },
    charli_360: {
        ...templateTraitsFrom('generic', 'charli_360', 'Reference-inspired Charli XCX 360 electropop traits; do not copy the full source script.'),
    },
    bug_from_heaven: {
        ...templateTraitsFrom('generic', 'bug_from_heaven', 'Reference-inspired Bug From Heaven guitar-song traits; do not copy the full source script.'),
    },
    stranger_things: {
        ...templateTraitsFrom('generic', 'stranger_things', 'Reference-inspired Stranger Things arpeggiated synth traits; do not copy the full source script.'),
    },
    pyramid_song: {
        ...templateTraitsFrom('generic', 'pyramid_song', 'Reference-inspired Pyramid Song piano and vocal-pad traits; do not copy the full source script.'),
    },
    rhythm_of_the_night: {
        ...templateTraitsFrom('generic', 'rhythm_of_the_night', 'Reference-inspired Rhythm of the Night Eurodance traits; do not copy the full source script.'),
    },
    pump_up_the_jam: {
        ...templateTraitsFrom('generic', 'pump_up_the_jam', 'Reference-inspired Pump Up The Jam 90s dance traits; do not copy the full source script.'),
    },
    happy_birthday: {
        ...templateTraitsFrom('generic', 'happy_birthday', 'Public-domain Happy Birthday melody traits with separated roles.'),
    },
    shostakovich_waltz: {
        ...templateTraitsFrom('generic', 'shostakovich_waltz', 'Reference-inspired Waltz #2 minor waltz traits; do not copy the full source script.'),
    },
    old_macdonald: {
        ...templateTraitsFrom('generic', 'old_macdonald', 'Traditional Old MacDonald melody traits with separated roles.'),
    },
    blue_monday: {
        ...templateTraitsFrom('generic', 'blue_monday', 'Reference-inspired Blue Monday machine-drum and synth-bass traits; do not copy the full source script.'),
    },
    undertale_determination: {
        ...templateTraitsFrom('generic', 'undertale_determination', 'Reference-inspired Determination chiptune traits; do not copy the full source script.'),
    },
    billie_birds: {
        ...templateTraitsFrom('generic', 'billie_birds', 'Reference-inspired Birds of a Feather soft-pop traits; do not copy the full source script.'),
    },
    generic: {
        genre: 'generic',
        aliases: template('generic').aliases,
        bpmRange: [96, 128],
        defaultBpm: 120,
        key: 'C minor',
        scale: 'C minor',
        drumFeel: 'Balanced beat unless the prompt suggests ambient or track-only.',
        bassRole: 'Simple root movement.',
        harmony: 'Safe minor loop.',
        leadRole: 'Short hook, not random notes.',
        soundPalette: ['909 drums', 'triangle bass', 'sine hook'],
        arrangement: 'Safe listenable loop.',
        density: 'balanced',
        requiredTracks: ['drums', 'bass', 'melody'],
        failureModes: ['style mismatch', 'robotic repetition', 'too many layers'],
    },
};

function templateTraitsFrom(baseGenre: GenreKey, genre: GenreKey, arrangement: string): GenreStyleTraits {
    const source = GENRE_TEMPLATES[genre];
    const base = GENRE_TEMPLATES[baseGenre] || source;
    const bpmRanges: Partial<Record<GenreKey, [number, number]>> = {
        rock: [124, 148],
        punk: [165, 188],
        metal: [140, 170],
        hiphop: [78, 104],
        dnb: [168, 178],
        drums: [90, 140],
        generic: [80, 140],
    };
    const baseDescriptions: Partial<Record<GenreKey, Pick<GenreStyleTraits, 'drumFeel' | 'bassRole' | 'harmony' | 'leadRole' | 'soundPalette' | 'density'>>> = {
        rock: {
            drumFeel: 'Rock-family backbeat with kick variations and clear snare anchors.',
            bassRole: 'Low root support locked to the riff.',
            harmony: 'Root/fifth guitar-like movement.',
            leadRole: 'Riff or chord chop with controlled distortion.',
            soundPalette: ['909 drums', 'sawtooth power chords', 'filtered bass'],
            density: 'balanced',
        },
        punk: {
            drumFeel: 'Fast hats and backbeat energy.',
            bassRole: 'Fast root-note drive.',
            harmony: 'Short power chords.',
            leadRole: 'Short aggressive riff.',
            soundPalette: ['tight drums', 'short saw chords', 'fast hats'],
            density: 'dense',
        },
        metal: {
            drumFeel: 'Tight kick pulse and strong snare.',
            bassRole: 'Low chug support.',
            harmony: 'Dark root/fifth chugs.',
            leadRole: 'Palm-muted low riff.',
            soundPalette: ['double kick', 'low saw chug', 'controlled distortion'],
            density: 'dense',
        },
        hiphop: {
            drumFeel: 'Punchy half-time kick/snare, dry clap support, and quiet uneven hats.',
            bassRole: 'Low 808-style sine bass under the beat.',
            harmony: 'Sparse minor color only.',
            leadRole: 'No lead melody by default; leave space for vocals unless requested.',
            soundPalette: ['808 kick', '909 snare', 'dry clap', 'quiet hats', 'low sine sub'],
            density: 'sparse',
        },
        dnb: {
            drumFeel: 'Fast broken beat.',
            bassRole: 'Rolling bass.',
            harmony: 'Minimal dark motif.',
            leadRole: 'Quiet top line.',
            soundPalette: ['breakbeat drums', 'filtered saw bass'],
            density: 'dense',
        },
        drums: {
            drumFeel: 'Kick, snare, and hats only.',
            bassRole: 'No bass.',
            harmony: 'No harmony.',
            leadRole: 'No melody.',
            soundPalette: ['synth kick', 'pink snare', 'quiet hats'],
            density: 'balanced',
        },
        generic: {
            drumFeel: 'Balanced groove.',
            bassRole: 'Simple root support.',
            harmony: 'Safe tonal progression.',
            leadRole: 'Hook or melody.',
            soundPalette: ['909 drums', 'synth bass', 'saw/sine hook'],
            density: 'balanced',
        },
    };
    const description = baseDescriptions[baseGenre] || baseDescriptions.generic!;
    return {
        genre,
        aliases: source.aliases,
        bpmRange: bpmRanges[baseGenre] || [Math.max(40, source.bpm - 8), Math.min(240, source.bpm + 8)],
        defaultBpm: source.bpm,
        key: source.key,
        scale: source.scale,
        drumFeel: description.drumFeel,
        bassRole: description.bassRole,
        harmony: description.harmony,
        leadRole: description.leadRole,
        soundPalette: description.soundPalette,
        arrangement,
        density: description.density,
        requiredTracks: source.requiredTracks,
        failureModes: [...base.qualityNotes, ...source.qualityNotes],
    };
}
